# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qg < Formula
  desc "generator thing"
  homepage "https://github.com/quinn/qg"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/quinn/qg/releases/download/v0.1.0/qg_Darwin_x86_64.tar.gz"
      sha256 "a386218f19e66fd82c6a44a4fd462b17d7f53cb223c8ece3c412d4d213f4feae"

      def install
        bin.install "qg"
      end
    end
    on_arm do
      url "https://github.com/quinn/qg/releases/download/v0.1.0/qg_Darwin_arm64.tar.gz"
      sha256 "feb08a60e6dd2f66db7f8aa7fba9578d459c13f0ee2d6d1dcb11ff1f09d54e50"

      def install
        bin.install "qg"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quinn/qg/releases/download/v0.1.0/qg_Linux_x86_64.tar.gz"
        sha256 "fc2864dc5a44f0f62f89502a061cba7e776e6b310b2aeff9d3053b9cda28473e"

        def install
          bin.install "qg"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quinn/qg/releases/download/v0.1.0/qg_Linux_arm64.tar.gz"
        sha256 "8b391e751f40ebaeb80cef1c26546a94ab462910ca0c97877ac71bca68542252"

        def install
          bin.install "qg"
        end
      end
    end
  end

  test do
    system "#{bin}/qg -help"
  end
end
